week-5 session-1 & week-5 session-3
Here is  a Bruno collection (open source alternate for postman) for API testing A1 to A6 bruno collection
On my system evaulate.py is throwing an error on A2 trying to execute npx on format.md before the llm is even invoked. However running the command directly on the command line works. evaluate.py: A2 failed: Command ‘[‘npx’, ‘prettier@3.4.2’, ‘–stdin-filepath’, ‘data/format.md’]’ returned non-zero exit status 2. A2 FAILED bash: npx prettier@3.4.2 --stdin-filepath data/format.md bash works as expected. Can someone help?
Error: Failed to process image URL 'https://emoji.discourse-cdn.com/google/red_circle.png?v=12' after 5 retries. Last error: 429 Client Error: Too Many Requests for url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDqHqkYWWr_VlNmsL-SYK4wKl4tPElJmhw
Error: Failed to process image URL 'https://emoji.discourse-cdn.com/google/x.png?v=12' after 5 retries. Last error: 429 Client Error: Too Many Requests for url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDqHqkYWWr_VlNmsL-SYK4wKl4tPElJmhw
@carlton Is there a maximum size limit for the Docker Image? Thanking you
@carlton @Jivraj Hi , I am trying to build using both docker and podman but it failed on both. I have watched many videos trying to resolve this adn also chatgpt in order to resolve the issue but it seems to persist. I even uninstalled and reinstalled both podman and doceker multiple times but no help. When i run command docker build -t ___________ . the error that comes is : Dockerfile:2 1 |     # Use a lightweight Python image 2 | >>> FROM python:3.12-slim 3 | 4 |     # Set the working directory in the container ERROR: failed to solve: python:3.12-slim: failed to resolve source metadata for Docker Hub Container Image Library | App Containerization failed to copy: httpReadSeeker: failed open: failed to do request: Get “ https://docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com/registry-v2/docker/registry/v2/blobs/sha256/6f/6f3c6367c5a38963f84310cbb24dfcfbddab1dad40cff18afb8fe89098891f08/data?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=f1baa2dd9b876aeb89efebbfc9e5d5f4%2F20250215%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20250215T192245Z&X-Amz-Expires=1200&X-Amz-SignedHeaders=host&X-Amz-Signature=ed37cf0c346e2ed440f29638ec43ce66640bdc7d285e7be7bf25c308c46fd6b1 ”: dialing docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com:443 container via direct connection because static system has no HTTPS proxy: connecting to docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com:443 : dial tcp: lookup docker-images-prod.6aa30f8b08e16409b46e0173d6de2f56.r2.cloudflarestorage.com : no such host Even tried getting python:3.12-slim separatly and trying again but that also didn’t work. I think there is some problem in getting python:3.12-slim as the build always stops at this. on asking ChatGPT it shows that some DNS or network issue is there. I even tried all the remedy that was provided on creating custom network etc. but this was also of no use Kindly help me finding solution to this and pls mention any other assistance I may require to get this running Thank You. Regards, Aagman
i am getting this error, I have tried many times but still the error persists: “message”: “Bearer YOUR_AIPROXY_TOKEN is invalid: JWSInvalid: Invalid Compact JWS”
someone please help!!!
@carlton needed a confirmation on this task A8 * `/data/credit-card.png` contains a credit card number. Pass the image to an LLM, have it extract the card number, and write it without spaces to `/data/credit-card.txt - in this task i assume prompt can ask for credit card number or other details like cvv and name. My question is, whether my system should allow prompt that CVV or or such info ? or should give it ?
Previously I asked for some more credits to test my project. I got an email stating I have been provided with a new token but I think I got that same token again, not a new one. I still cant send request to the AIPROXY. Please help. Do I need to submit the docker image name with the tag or without the tag? I submitted it before without the tag. Now i see that I have tagged the image with as v1 but I cant submit the form due to pattern matching problems. Should i submit again after tagging it with :latest ? @s.anand @carlton @Jivraj
@Jivraj @carlton sir in the phase B will the input and output path will be given ?
@carlton @Jivraj @Saransh_Saini When I run my docker image using podman run -e AIPROXY_TOKEN=$AIPROXY_TOKEN -p 8000:8000 $IMAGE_NAME Task A2 fails as the podman container is unable to find npx. Running the same image using docker run -e AIPROXY_TOKEN=$AIPROXY_TOKEN -p 8000:8000 $IMAGE_NAME works fine and Task A2 passes. I can’t understand why this is happening. I also ran the image in both docker and podman in interactive mode as show in the below snippet from terminal. When run using docker, which node gives /usr/bin/node as output but when run using podman, nothing. shiva@shiva:~/Desktop/tdsp1$ sudo podman run --rm -it docker.io/myusername/myreponame /bin/sh
# echo $PATH
/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# which node
# exit
shiva@shiva:~/Desktop/tdsp1$ sudo docker run --rm -it docker.io/myusername/myreponame /bin/sh
# echo $PATH
/root/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
# which node
/usr/bin/node
# exit
shiva@shiva:~/Desktop/tdsp1$ sudo podman run --user=root --rm -it docker.io/myusername/myreponame /bin/sh
# which node
# which node
# exit
Here’s how to prompt folks. Just do what @carlton mentioned in today’s live session (the 5 hour marathon) and you should be good for Project-1! x.com Aakash Gupta @aakashg0 Most people are still prompting wrong.

I've found this framework, which was even shared by OpenAI President Greg Brockman.

Here’s how it works: pic.x.com/2MMcEqBeIJ 8:06 PM - 14 Feb 2025 5.5K 360
Error: Failed to process image URL 'https://europe1.discourse-cdn.com/flex013/uploads/iitm/original/3X/6/7/67f2a2d0db391947304ab4e006d7ea42c3b8850d.jpeg' after 5 retries. Last error: 429 Client Error: Too Many Requests for url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDqHqkYWWr_VlNmsL-SYK4wKl4tPElJmhw
Error: Failed to process image URL 'https://europe1.discourse-cdn.com/flex013/uploads/iitm/optimized/3X/c/e/ce7a62f2fa1f33758771e9ef57dd90fe2d98b09d_2_502x500.jpeg' after 5 retries. Last error: 429 Client Error: Too Many Requests for url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=AIzaSyDqHqkYWWr_VlNmsL-SYK4wKl4tPElJmhw
Same issue. Got the same token. Can’t use it since 2 dollar limit has been crossed. Please help. @carlton @Jivraj
Yes I also need the answer of this.
Is there any way of figuring what is the usage of my token and if yes then how… Plz some peers help…
It will be corrected soon by @jkmadathil He is in charge of our budget for TDS and the tokens are being issued by him. Please tag him for any token related issues.
New token assigned to the students.  Emails are also sent.
sir I am noticing a pattern, that when I am running the datagen first. And then using the evaluate.py, then I am getting the A2 right. But running the evaluation.py for the 2nd time cause the A2 to fail… Probabbly Because the file in the data folder gets upated should I worry for that…
in the phase B, we have no idea about how many arguments are there, so should we make every function mapping with 2 arguments ( 1 containing the input location and other containing output location) or should we take the parameters in some other way
There has been an outage in some parts of the country related to cloudflare servers. What helped some students (and us) is using a completely different network eg. instead of using your home wifi, use mobile internet, since they go through a different DNS and this sometimes works. Kind regards
